config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :rooms do
    collection do
      get 'search'
    end
  end
  resources :bookings do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id', optional: true
  belongs_to :room, foreign_key: 'room_id', optional: true
 
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id', optional: true
  belongs_to :booking, foreign_key: 'booking_id', optional: true
  has_one_attached :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable       
         
  has_one_attached :image
  has_many :rooms, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  def set_search
    @search = Room.ransack(params[:q])
    @results = @search.result
  end
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @room = Room.find_by(id: params[:format])
  end

  def confirm
    @booking = Booking.create(booking_params)
    @room = Room.find(@booking.room_id)
    @booking.days = (@booking.last_date - @booking.start_date)
    @booking.allcost = @room.cost * @booking.people * @booking.days
    if @booking.invalid? 
    end
  end

  def create
    @booking = Booking.create(booking_params)
    @booking.days = (@booking.last_date - @booking.start_date)
    @booking.allcost = @room.cost * @booking.people * @booking.days
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render "new"
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.days = (@booking.last_date - @booking.start_date)
    @room = Room.find(@booking.room_id)
    @booking.allcost = @room.cost * @booking.people * @booking.days
      if @booking.update(booking_params)
        flash[:notice] = "予約（ID:「#{@booking.id}」）が完了しました"
        redirect_to booking_path
      else
        render "new"
      end

  end

  def index
    @bookings = Booking.all
    @rooms = Room.all
  end

  def show
    @booking = Booking.find(params[:id])
    @room = Room.find(@booking.room_id)
  end

  def edit
  end

  


  private
  def booking_params
    params.require(:booking).permit(:user_id, :room_id, :start_date, :last_date, :people, :days, :allcost)
  end
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
  end

  def new
    @room = Room.new(params.permit(:roomname, :roomabout, :cost, :address, :image, :user_id))
  end

  def create
    @room = Room.create(room_params)
    @room.user_id = current_user.id
    if @room.save
      redirect_to new_booking_path(@room.id)
    else
      render "new"
    end
  end

  def search
    @results = @search.result
  end

  private
  def room_params
    params.require(:room).permit(:roomname, :roomabout, :cost, :address, :image, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user =User.find(params[:id])
  end

  def edit
    @user =User.find(params[:id])
    @user_id = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to edit_user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/confirm.html.erb
<div class="confirm-all">
  <h2 class="conf-h2">予約内容確認</h2>

  <div class="confirm-about">
    <%= form_for @booking do |f| %>
      <div class="conf-cost">
        <p class="booking-label">¥<%= @room.cost %>/日</p>
      </div>
      <div class="start-day">
        <p class="booking-label">開始日</p>
        <%= @booking.start_date %>
      </div>

      <div class="last-day">
        <p class="booking-label">終了日</p>
        <%= @booking.last_date %>
      </div>

      <div class="rental-days">
        <p class="booking-label">使用日数</p>
        <p><%= @booking.days %>日</p>
      </div>

      <div class="people">
        <p class="booking-label">人数</p>
        <p><%= @booking.people %>人</p>
      </div>

      <div class="all-cost">
        <p class="booking-label">合計金額</p>
        <p><%= @booking.allcost %>円</p>
      </div>

      <p class="conf-info">上記の内容でよろしければ「予約確定」を押してください</p>
      ___________________________________________________________
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <%= f.hidden_field :booking_id, value: @booking.id %>
      <div class="conf-submit">
        <%= f.submit "予約確定" %><br>
      </div>

      <%= link_to "ルーム詳細に戻る", room_path(@booking.room_id) %>
      
      <% end %>
  </div>
    
</div>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<h1 class="h1">予約済みルーム一覧</h1>
<div class="booking-list">
  <table>
      <thead>
        <tr>
          <th>ルーム画像</th>
          <th>ルーム名</th>
          <th>ルーム紹介</th>
          <th>合計金額</th>
          <th>開始日</th>
          <th>終了日</th>
          <th>予約確定日時</th>
        </tr>
      </thead>
 
      <tbody>
        <div class="all-bookings">
          <div class="room-booking">
            <% @rooms.each do |room| %>
            <% @bookings.each do |booking| %>
              <tr>
                <td class="r-img"><%= image_tag room.image if room.image.attached? %></td>
                <td><%= room.roomname %></td>
                <td><%= room.roomabout %></td>
                <td><%= booking.allcost %>円</td>
                <td><%= booking.start_date %></td>
                <td><%= booking.last_date %></td>
                <td><%= booking.created_at %></td>
              </tr>
            <% end %>
            <% end %>
          </div>
        </div>
      </tbody>
    </table>
</div>

app/views/bookings/new.html.erb
<div class="room-show-all">
  <div class="room-page-left">
    
      <div class="room-img">
        <% if @room.image.attached? %>
          <%= image_tag @room.image %>
        <% end %><br>
      </div>

      <div class="room-name">
        <p>ルーム名</p>
        <%= @room.roomname %><br>
      </div>

      <div class="room-address">
        <p>住所</p>
        <%= @room.address %><br>
      </div>

      <div class="room-about">
        <%= simple_format @room.roomabout %><br>
      </div>
  </div>

  <div class="room-page-right">
  
    <div class="room-cost">
      <p>¥ <%= @room.cost %> /日</p>
    </div>
    
    <%= form_for @booking, url: confirm_bookings_path(@booking) do |f| %>
      <div class="start-day">
        <%= f.label :start_date, "開始日" %>
        <%= f.date_field :start_date %>
      </div>

      <div class="end-day">
        <%= f.label :last_date, "終了日" %>
        <%= f.date_field :last_date %>
      </div>

      <div class="count">
        <%= f.label :people, "人数" %>
        <%= f.number_field :people %>
      </div>

      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <%= f.hidden_field :booking_id, value: @booking.id %>


      <div class="reserve">
        <%= f.submit "予約する" %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="booking-show-all">

  <div class="booking-show-about">

    <div class="show-roomname">
      <p class="booking-label">予約した部屋</p>
      <%= @room.roomname %>
    </div>

    <div class="show-start">
      <p class="booking-label">開始日</p>
      <%= @booking.start_date.strftime("%Y年%m月%d日") %>
    </div>

    <div class="show-last">
      <p class="booking-label">終了日</p>
      <%= @booking.last_date.strftime("%Y年%m月%d日") %>
    </div>

    <div class="show-allcost">
      <p class="booking-label">合計金額</p>
      <p><%= @booking.allcost %>円</p>
    </div>

  </div>
    
</div>
  

app/views/home/index.html.erb
<div class="top-all">
  <div class="top-first">
    <div class="center-search">
      <p>Potepan Shareでまだ体験したことのない旅をしよう</p>
      <%= search_form_for @search, url: search_rooms_path do |f| %>
        <%= f.label :address_cont, "エリア" %><br>
       
        <div class="address-cont">
          <%= f.search_field :address_cont %>
        </div>
        <div class="center-submit">
          <%= f.submit '検索' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="top-second">
    <div class="second-p">
      <p>おすすめのエリア</p>
    </div>

    <div class="recomend">
      <div class="tokyo">
        <p>東京</p>
      </div>
      <div class="osaka">
        <p>大阪</p>
      </div>
      <div class="kyoto">
        <p>京都</p>
      </div>
      <div class="sapporo">
        <p>札幌</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">
    <%= render 'shared/header' %>
    <%= render 'shared/toast' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/rooms/edit.html.erb
<h1>Rooms#edit</h1>
<p>Find me in app/views/rooms/edit.html.erb</p>

app/views/rooms/index.html.erb
<h1 class="h1">登録済みルーム一覧</h1>
<div class="room-list">
  <table>
      <thead>
        <tr>
          <th>ルーム画像</th>
          <th>ルーム名</th>
          <th>ルーム紹介</th>
          <th>料金</th>
          <th>作成日</th>
        </tr>
      </thead>
 
      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td class="r-img"><%= image_tag room.image if room.image.attached? %></td>
            <td>
              <%= link_to new_booking_path(room.id) do %>
                <%= room.roomname %>
              <% end %>
            </td>
            <td><%= room.roomabout %></td>
            <td><p>¥<%= room.cost %>円</p></td>
            <td><%= room.created_at.strftime("%Y-%m-%d %H:%M") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/rooms/new.html.erb
<div class="rooms-page-all">
  <h1>ルーム情報登録</h1>

  <%= form_for @room do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="rooms-field">
      <%= f.label :roomname, "ルーム名" %>
      <%= f.text_field :roomname %>
    </div>
    <div class="rooms-field">
      <%= f.label :roomabout, "ルーム紹介" %><br>
      <%= f.text_area :roomabout %>
    </div>
    <div class="rooms-field">
      <%= f.label :cost, "料金" %><br>
      <%= f.number_field :cost %>
    </div>
    <div class="rooms-field">
      <%= f.label :address, "住所" %>
      <%= f.text_field :address %>
    </div>

    <div class="rooms-field">
      <%= f.label :image, "ルーム画像" %><br>
      <%= f.file_field :image %><br>
    </div>

    <div class="rooms-field">
      <%= f.submit "登録する" %>
    </div>
  <% end %>
</div>

app/views/rooms/search.html.erb
<div class="search-header">
  <h2 >検索結果</h2>
</div>

<div class="serch-all">
  <div class="search-about"> 
    <div class="table">
      <% @results.each do |room| %>
       <div class="data">

        <%= link_to new_booking_path(room.id) do %>
          <% if room.image.attached? %>
            <%= image_tag room.image %>
          <% end %><br>
        <% end %>

        <%= link_to new_booking_path(room.id) do %>
          <%= room.roomname %>
        <% end %><br>

        <%= room.address %>

        <p>¥ <%= room.cost %> /日</p><br>
       </div><br>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="room-show-all">
  <div class="room-page-left">
    <%= form_for(@room) do |f| %>
      
      <div class="room-img">
        <% if @room.image.attached? %>
          <%= image_tag @room.image %>
        <% end %><br>
      </div>
    
      <div class="room-name">
        <p>ルーム名</p>
        <%= @room.roomname %><br>
      </div>

      <div class="room-address">
        <p>住所</p>
        <%= @room.address %><br>
      </div>

      <div class="room-about">
        <%= simple_format @room.roomabout %><br>
      </div>
    <% end %>
  </div>

  <div class="room-page-right">
  
    <div class="room-cost">
      <p>¥ <%= @room.cost %> /日</p>
    </div>
  </div>
</div>
    

app/views/shared/_footer.html.erb
<div id="footer">
  <p>©︎ 2020 POTEPAN.INC</p>
</div>

app/views/shared/_header.html.erb
<div id="header">
  <div class="logo">
    <%= link_to root_path, class: "navbar-item" do %>
      <h1 class="title is-4" style="font-family: cursive;">Pote Share</h1>
    <% end %>
  </div>

  <%= search_form_for @search, url: search_rooms_path do |f| %>
    <%= f.label :roomname_or_introduction_or_address_cont, "キーワード" %>
    <%= f.search_field :address_or_roomname_or_roomabout_cont %>
  <% end %>

  <%= search_form_for @search, url: search_rooms_path do |f| %>
    <%= f.label :address_cont, "エリア" %>
    <%= f.search_field :address_cont %>
  <% end %>

  <div class="link">
    <ul id="nav">
      <% if user_signed_in? %>
        <li>
          <div class="gnavi__wrap">
            <ul class="gnavi__lists">
              <li class="gnavi__list">
                  <a href="#">メニュー</a>
                  <ul class="dropdown__lists">
                    <div class="dropdown__list">
                      <%= link_to "ルーム情報登録", new_room_path %>
                    </div>
                    <div class="dropdown__list">
                      <%= link_to "予約済みルーム一覧", bookings_path %>
                    </div>
                    <div class="dropdown__list">
                      <%= link_to "登録済みルーム一覧", rooms_path %>
                    </div>
                    <div class="dropdown__list">
                      <%= link_to "アカウント編集", edit_user_registration_path %>
                    </div>
                    <div class="dropdown__list">
                      <%= link_to "プロフィール編集", edit_user_path(current_user) %> 
                    </div>
                  </ul>
              </li>
            </ul>
          </div>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :get %>
        </li>
      <% else %>
        <li>
          <%= link_to "ログイン", new_user_session_path %>
        </li>
        <li>
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_toast.html.erb
<% if flash[:notice].present? %>
  <div class="toast">
    <div class="notice"><%= notice %></div>
  </div>
<% end %>

<% if flash[:alert].present? %>
  <div class="toast">
    <div class="alert"><%= alert %></div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="users-page-all">
  <h1>プロフィール編集</h1>

  <%= form_for @user do |f| %>
    
    <div class="user-image">
      <% if @user.image.attached? %>
        <%= image_tag @user.image %>
      <% end %>
    </div>

    <div class="users-field">
      <%= f.label :image, "アイコン画像" %><br>
      <%= f.file_field :image %>
    </div>

    <div class="users-field">
      <%= f.label :username, "ユーザー名" %>
      <%= f.text_field :username %>
    </div>
    <div class="users-field">
      <%= f.label :introduction, "自己紹介" %>
      <%= f.text_area :introduction %>
    </div>
    <div class="users-field">
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email %>
    </div>

    <div class="users-actions">
      <%= f.submit "編集する" %>
    </div>

  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<%= @users.each do |user| %>
<%= user.username %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= @user.username %>

<%= @user.email %>

<%= @user.introduction %>

<%= link_to "編集", edit_user_path(@user) %>